# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-15 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import molo.core.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks
import wagtailschemaorg.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_auto_20180906_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedArticlePage',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ArticlePage')),
                ('structured_data', wagtail.wagtailcore.fields.StreamField((('faq', wagtail.wagtailcore.blocks.StructBlock((('title_for_faq', wagtail.wagtailcore.blocks.CharBlock()), ('question_and_answer', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('question', wagtail.wagtailcore.blocks.CharBlock()), ('answer', wagtail.wagtailcore.blocks.CharBlock())))))), icon='help', max_num=1)), ('how_to', wagtail.wagtailcore.blocks.StructBlock((('title_for_how_to', wagtail.wagtailcore.blocks.CharBlock()), ('image_when_finished', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('description', molo.core.blocks.MarkDownBlock(required=False)), ('estimated_cost', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('materials_required', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.CharBlock(label='material'), default=[])), ('tools_required', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.CharBlock(label='tool'), default=[])), ('steps', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('step_name', wagtail.wagtailcore.blocks.CharBlock()), ('step_image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('step_parts', wagtail.wagtailcore.blocks.StreamBlock((('instruction', wagtail.wagtailcore.blocks.CharBlock()), ('suggestion', wagtail.wagtailcore.blocks.CharBlock()))))))))), icon='list-ul', max_num=1))), blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailschemaorg.models.PageLDMixin, 'core.articlepage'),
        ),
    ]
