# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-29 20:39
from __future__ import unicode_literals

from django.db import migrations
import molo.core.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('schemapages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedarticlepage',
            name='structured_data',
            field=wagtail.wagtailcore.fields.StreamField((('faq', wagtail.wagtailcore.blocks.StructBlock((('title_for_faq', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('question_and_answer', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('question', wagtail.wagtailcore.blocks.CharBlock()), ('answer', wagtail.wagtailcore.blocks.CharBlock())))))), icon='help', max_num=1)), ('how_to', wagtail.wagtailcore.blocks.StructBlock((('title_for_how_to', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('image_when_finished', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('description', molo.core.blocks.MarkDownBlock(required=False)), ('estimated_cost', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('materials_required', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.CharBlock(label='material'), default=[])), ('tools_required', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.CharBlock(label='tool'), default=[])), ('steps', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('step_name', wagtail.wagtailcore.blocks.CharBlock()), ('step_image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('step_parts', wagtail.wagtailcore.blocks.StreamBlock((('instruction', wagtail.wagtailcore.blocks.CharBlock()), ('suggestion', wagtail.wagtailcore.blocks.CharBlock())), required=False))))))), icon='list-ul', max_num=1))), blank=True, null=True),
        ),
    ]
