# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 14:26
from __future__ import unicode_literals

from django.db import migrations


def create_group(apps, schema_editor):
    Group = apps.get_model('auth.Group')
    Permission = apps.get_model('auth.Permission')

    # Create M&E specialist Group
    me_specialist, created = Group.objects.get_or_create(name='M&E specialist')

    edit_groups = Permission.objects.get(codename='change_group')
    access_admin = Permission.objects.get(codename='access_admin')
    delete_groups = Permission.objects.get(codename='delete_group')

    add_language = Permission.objects.get(
        codename='add_languagerelation')
    edit_language = Permission.objects.get(
        codename='change_languagerelation')
    delete_language = Permission.objects.get(
        codename='delete_languagerelation')

    add_securityquestion = Permission.objects.get(
        codename='add_securityquestion')
    edit_securityquestion = Permission.objects.get(
        codename='change_securityquestion')
    delete_securityquestion = Permission.objects.get(
        codename='delete_securityquestion')

    add_survey = Permission.objects.get(
        codename='add_personalisablesurvey')
    edit_survey = Permission.objects.get(
        codename='change_personalisablesurvey')
    delete_survey = Permission.objects.get(
        codename='delete_personalisablesurvey')

    edit_comment = Permission.objects.get(
        codename='change_molocomment')
    reply_comment = Permission.objects.get(
        codename='add_reactionquestionresponse')
    delete_comment = Permission.objects.get(
        codename='delete_molocomment')

    add_cannedresponse = Permission.objects.get(
        codename='add_cannedresponse')
    edit_cannedresponse = Permission.objects.get(
        codename='change_cannedresponse')
    delete_cannedresponse = Permission.objects.get(
        codename='delete_cannedresponse')

    add_poll = Permission.objects.get(codename='add_pollsindexpage')
    edit_poll = Permission.objects.get(codename='change_pollsindexpage')
    delete_poll = Permission.objects.get(codename='delete_pollsindexpage')

    add_choicevote = Permission.objects.get(codename='add_choicevote')
    edit_choicevote = Permission.objects.get(codename='change_choicevote')
    delete_choicevote = Permission.objects.get(codename='delete_choicevote')

    add_molosurveysubmission = Permission.objects.get(codename='add_molosurveysubmission')
    edit_molosurveysubmission = Permission.objects.get(codename='change_molosurveysubmission')
    delete_molosurveysubmission = Permission.objects.get(codename='delete_molosurveysubmission')

    me_specialist.permissions.add(
        access_admin,
        edit_groups, delete_groups,
        add_cannedresponse,
        edit_cannedresponse,
        delete_cannedresponse,
        add_securityquestion,
        edit_securityquestion,
        delete_securityquestion,
        add_poll, edit_poll, delete_poll,
        add_survey, edit_survey, delete_survey,
        edit_comment, reply_comment, delete_comment,
        add_language, edit_language, delete_language,
        add_choicevote, edit_choicevote, delete_choicevote,
        add_molosurveysubmission, edit_molosurveysubmission, delete_molosurveysubmission
    )


class Migration(migrations.Migration):

    dependencies = [
        ('iogt', '0003_convert_recomended_articles'),
    ]

    operations = [migrations.RunPython(create_group)]
